// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIj8vQA6tE8k0R0Y5ZhQNeIZe8dKlBSRc',
    appId: '1:552691628652:web:c448d2b3c120874dfe3649',
    messagingSenderId: '552691628652',
    projectId: 'absen-150e3',
    authDomain: 'absen-150e3.firebaseapp.com',
    storageBucket: 'absen-150e3.firebasestorage.app',
    measurementId: 'G-Y68F6JDGKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVaWC22zU9OtzPc2_WqgMlqU5TL6Nml6k',
    appId: '1:552691628652:android:74ea11317f4de128fe3649',
    messagingSenderId: '552691628652',
    projectId: 'absen-150e3',
    storageBucket: 'absen-150e3.firebasestorage.app',
  );
}
